### PR TITLE
Fix deprecated 'use Bitwise'

### PR DESCRIPTION
**Pull request by dvic**

### CODE REVIEW

**Comment by dvic** [comment]
See https://github.com/elixir-lang/elixir/blob/v1.14/CHANGELOG.md#4-hard-deprecations

**Comment by dvic** [comment]
(in `lib/mongo.ex` it was unused, so I removed it)

**Comment by zookzook** [comment]
Thanks for the PR. What about older Elixir versions? What is the minimal version of Elixir that would work with the changes?

**Comment by dvic** [comment]
I think it's fully backwards compatible, the old logic was:

https://github.com/elixir-lang/elixir/blob/0909940b04a3e22c9ea4fedafa2aac349717011c/lib/elixir/lib/bitwise.ex#L26-L42

So I guess this goes from `import Bitwise, except: []` to `import Bitwise`

**Comment by zookzook** [comment]
Thank you!

**Pull request merged**
