### PR TITLE
Adds options argument to some functions

### PR DESCRIPTION
**Pull request by ksmithut**
There were some functions in the Repo module that did not accepts options. Some of those options (such as :database) are important to be able to pass through to the underlying Mongo functions.

I'm not sure if this is the right way to implement this. I'm fairly new to behaviors so I'm not sure if changing the arity of those functions is a breaking change. Any suggestions would be welcome. It's a small thing, so I'm also happy to start over if this needs to be done completely differently.

### CODE REVIEW

**Review by zookzook — APPROVED** [review]

**Comment by zookzook** [comment]
Thank you. I think the additional option parameter is always a good feature. Maybe we can extend it to use the process dictionary for the database entry, so you can use nested function calls.

Can you fix the credo issue please?
```
[W] ↗ There should be no unused return values for Keyword functions.

```

**Comment by ksmithut** [comment]
@zookzook I definitely should have run credo, definitely caught a bug :)

> Maybe we can extend it to use the process dictionary for the database entry, so you can use nested function calls.

My thoughts exactly. I'll propose an idea after this is in.

**Review by zookzook — APPROVED** [review]
Thank you!

**Comment by ksmithut** [comment]
@zookzook alright, I think I've got all that figured out. Thanks for your patience :)

**Comment by zookzook** [comment]
Thank you!

**Pull request merged**
