### PR TITLE
Use erlef/setup-beam for GitHub Actions

### PR DESCRIPTION
**Pull request by kianmeng**
Remove the extra redirection. See https://github.com/erlef/setup-beam/issues/20

### CODE REVIEW

**Comment by zookzook** [comment]
Thank you. To merge the PR I need a signed commit. But if this is too much effort, I can commit it if you like.

**Comment by kianmeng** [comment]
@zookzook Done. Please check.

**Comment by zookzook** [comment]
Sorry, didn't work. There is no "verify" mark.

**Comment by kianmeng** [comment]
@zookzook I see. Can you help to commit? Thanks.

**Comment by zookzook** [comment]
Did you check all the steps mentioned here: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by kianmeng** [comment]
@zookzook Thanks, and done. Please check again.

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
